"""Single source of truth for every published number: the flip-contrast SVG
and the README AUTOGEN block, both rendered from metrics.jsonl. CI regenerates
and `git diff --exit-code` fails the build on any drift.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

AUTOGEN_BEGIN = "<!-- AUTOGEN:BEGIN — rendered by report.py from metrics.jsonl; do not edit by hand -->"
AUTOGEN_END = "<!-- AUTOGEN:END -->"
DISCLAIMER = "scripted judges — the contrast proves the instrument, not any model's calibration"

_BLUE = "#2563eb"
_RED = "#dc2626"


@dataclass(frozen=True)
class Metrics:
    chamber: dict[str, object]
    flips: list[dict[str, object]]


def load_metrics(path: Path) -> Metrics:
    chamber: dict[str, object] = {}
    flips: list[dict[str, object]] = []
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            row = json.loads(line)
            if row["kind"] == "chamber":
                chamber = row
            else:
                flips.append(row)
    return Metrics(chamber=chamber, flips=flips)


def render_flip_svg(metrics: Metrics) -> str:
    """Two bars: each judge's flip count out of the same item total."""
    rows = sorted(metrics.flips, key=lambda r: str(r["judge"]))
    width, row_h, top, bottom, left, right = 760, 44, 64, 92, 220, 90
    height = top + row_h * len(rows) + bottom
    bar_w = width - left - right
    total = max(int(r["total"]) for r in rows) if rows else 1  # type: ignore[arg-type]

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" font-family="monospace" font-size="12">',
        f'<rect width="{width}" height="{height}" fill="#ffffff"/>',
        f'<text x="{left}" y="22" font-size="14" fill="#111111">'
        "the flip test — verdicts changed by flipping ONLY the default instruction</text>",
        f'<text x="{left}" y="40" fill="#6b7280">'
        f"same {total} proposals, same objections; only the standing presumption differs</text>",
    ]
    for i, row in enumerate(rows):
        y = top + i * row_h
        flips = int(row["flips"])  # type: ignore[arg-type]
        frac = flips / total if total else 0.0
        color = _BLUE if flips == 0 else _RED
        parts.append(
            f'<text x="{left - 10}" y="{y + 22}" text-anchor="end" fill="#111111">'
            f"{row['judge']}</text>"
        )
        parts.append(
            f'<rect x="{left}" y="{y + 8}" width="{bar_w}" height="20" '
            f'fill="#f1f5f9" stroke="#e5e7eb"/>'
        )
        if frac > 0:
            parts.append(
                f'<rect x="{left}" y="{y + 8}" width="{bar_w * frac:.1f}" height="20" '
                f'fill="{color}"/>'
            )
        parts.append(
            f'<text x="{left + bar_w + 8}" y="{y + 22}" fill="#111111">'
            f"{flips}/{total} flipped</text>"
        )
    base_y = top + row_h * len(rows) + 26
    parts.append(
        f'<text x="{left}" y="{base_y}" fill="#991b1b">{DISCLAIMER}</text>'
    )
    parts.append(
        f'<text x="{left}" y="{base_y + 20}" fill="#6b7280">'
        "a verdict that flips with the instruction was never a verdict about "
        "the evidence</text>"
    )
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def render_claims(metrics: Metrics) -> str:
    ch = metrics.chamber
    by_judge = {str(r["judge"]): r for r in metrics.flips}
    evidence = by_judge.get("EvidenceJudge", {})
    deferential = by_judge.get("DeferentialJudge", {})
    lines = [
        "| claim | number (regenerated by CI) | how measured | honest caveat |",
        "|---|---|---|---|",
        (
            "| Every verdict carries its cause of death "
            f"| **{ch['verdicts']} verdicts ledgered: {ch['kills']} kills, "
            f"{ch['survivals']} survivals — {ch['reasons_logged']} written reasons, "
            "0 empty** | the chamber refuses a verdict without a written reason; "
            "the ledger is one JSON line per verdict | conformance of the harness — "
            "the scripted judges' reasons are rule-generated, not model judgment |"
        ),
        (
            "| The flip test detects an instruction-following judge "
            f"| **DeferentialJudge: {deferential.get('flips')}/"
            f"{deferential.get('total')} verdicts flipped when only the default "
            "instruction changed** | identical proposals and objections judged "
            "under presume-dies then presume-survives; within-item outcome "
            "comparison | the judge is BUILT to defer on ambiguous items — this "
            "proves the instrument lights up, not that any real judge behaves "
            "this way |"
        ),
        (
            "| ...and stays dark on an evidence-driven judge "
            f"| **EvidenceJudge: {evidence.get('flips')}/{evidence.get('total')} "
            "flipped under the same test** | same procedure, same items | "
            "instruction-insensitivity here is by construction (fixed tie-break); "
            "a live judge earns this number, it is not granted |"
        ),
        (
            "| Ambiguity is where instructions take over "
            f"| **{ch['ambiguous_items']} of {ch['proposals']} fixture proposals "
            "are ambiguous, and they are exactly the flipped set** | ambiguity = "
            "evidence margin under the clear threshold; the flipped ids equal the "
            "ambiguous ids (asserted by test) | on clear evidence both judges "
            "agree regardless of instruction — the danger zone is precisely the "
            "cases that need judgment most |"
        ),
    ]
    return "\n".join(lines)


def inject_readme(readme_path: Path, block: str) -> None:
    text = readme_path.read_text(encoding="utf-8")
    begin = text.index(AUTOGEN_BEGIN)
    end = text.index(AUTOGEN_END) + len(AUTOGEN_END)
    new = text[:begin] + AUTOGEN_BEGIN + "\n\n" + block + "\n\n" + AUTOGEN_END + text[end:]
    with readme_path.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(new)
